name: Exhaustive checks

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

# For a PR #7488 against main branch, the `group` will become: CI-{{ 7488 || github.sha }}
# which eventually evaluates to: CI-7488 and 'sha' isn't used.
# NOTE: `||` acts as a logical OR and a default operator both,
# see: https://docs.github.com/en/actions/learn-github-actions/expressions#operators.
# When it isn't a PR against main but instead a commit pushed (or merged) to main, then `group` will
# evaluate to `${{ github.sha }}` but "cancel-in-progress" evaluates to false, so the CI on main
# will run in a new group `${{ github.sha }}`, but no previous CI will be cancelled on main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


env:
  MACOSX_DEPLOYMENT_TARGET: 14.0

jobs:
  debug_outOfSource:
    name: Check Out-of-Source Debug build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src

      - uses: mamba-org/setup-micromamba@v1.8.0
        with:
          micromamba-version: '1.5.10-0'
          environment-file: src/ci/environment_linux.yml
          create-args: >-
            python=3.10

      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Build Linux
        shell: bash -e -l {0}
        run: |
            ( cd src && ./build0.sh )
            export CXXFLAGS="-Werror"
            cmake -S src -B builddir -GNinja \
              -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DWITH_LLVM=yes \
              -DWITH_LSP=yes \
              -DWITH_KOKKOS=yes \
              -DLFORTRAN_BUILD_ALL=yes \
              -DWITH_STACKTRACE=no \
              -DWITH_RUNTIME_STACKTRACE=yes \
              -DCMAKE_PREFIX_PATH="$CONDA_PREFIX" \
              -DCMAKE_INSTALL_PREFIX=`pwd`/inst \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

            cmake --build builddir  -j16 --target install

      - name: Test Linux
        shell: bash -e -l {0}
        run: ctest --output-on-failure
        working-directory: builddir

      - name: Test Moved Installation
        shell: bash -e -l {0}
        run: |
          mv inst inst.moved
          cp src/examples/expr2.f90 expr2.F90
          rm -rf src
          inst.moved/bin/lfortran expr2.F90 -o expr2
          ./expr2
          inst.moved/bin/lfortran --backend=c expr2.F90 -o expr2b
          ./expr2b
          inst.moved/bin/lfortran --openmp --backend=cpp expr2.F90 -o expr2c
          ./expr2c

